sylius_grid:
    templates:
        bulk_action:
            edit: "@TahirRasheedSyliusBulkEditPlugin/grid/bulk_action/edit.html.twig"

    grids:
        sylius_admin_product:
            actions:
                bulk:
                    edit:
                        type: edit
                        label: Edit Price
                        options:
                            link:
                                route: sylius_bulk_edit_admin_bulk_edit_products
